### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by asd646942825** [ryanreadbooks/VotingNet6DPose#1]
请问数据集在哪下载？谢谢

**Comment by ryanreadbooks** [comment]
时间有点久了，不太记得。印象中好像是[这个仓库里](https://github.com/Microsoft/singleshotpose/)找的数据集。

**Comment by asd646942825** [comment]
您好，您提供的这个仓库里的数据库我都下载好了。但是您程序里求fps点，需要.xyz文件。但是linemod里没有这个文件，只有.ply文件，所以我不太懂您用的是什么数据集呢？非常急用，十分感谢您耐心的回复

**Comment by asd646942825** [comment]
还请问一下，您的程序里面还需要gt_poses的是不是linemod数据集里的pose中.npy文件呢？因为只找到一个相关的linemod数据集，但是你程序里设计的文件，这个数据集又没有。

**Comment by ryanreadbooks** [comment]
gt_poses文件夹里面是原始linemod数据集里面的.rot和.tra文件；模型的.ply文件也是原始linemod里面的。

**Comment by asd646942825** [comment]
您是将linemod数据集里的一些文件名改了吗？那请问一下，您还有这个改了的数据集吗？
因为原始linemod数据集没有.rot和.tra文件夹，只有labels,label_occlusion，mask,pose等文件夹和.txt,.pkl结尾的文件。
我想请问一下，您还记得gt_poses里是什么文件吗？是不是pose文件夹里的.npy文件还是labels文件夹里的.txt文件

**Comment by ryanreadbooks** [comment]
这个是当时做的数据集，当时只做了cat这个类，你试下这个吧。https://pan.baidu.com/s/1mJMb1im8Xk-tC6Fq-LODOQ 提取码: 491s

**Comment by asd646942825** [comment]
哦哦，好的好的，十分感谢您！您是真的强，那个PVNet我都没调好。你竟然还能改出来！

**Comment by dcf123-ff** [comment]
您好，我也在学您的代码。我也遇到了.xyz文件找不到的问题，您的百度网盘链接已经失效了，可以重新提供一下吗？万分感谢您
